[book]
authors = ["bryanjimenez"]
language = "en"
src = "src"
title = "nmemonica Documentation"

[build]
build-dir = "../dist/docs"

[output.html]
git-repository-url = "https://github.com/bryanjimenez/nmemonica"

[output.html.fold]
enable = true